### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by whoot** [ttimasdf/XDebuggable#2]
Hey,

i can´t install the app. Nor via XPosed Framework or via adb.
When I try to install it via XPosed Framework, Xposed just says: "App was not installed".
When I try to install the app via adb the following error occurs:

```
adb install debuggable.apk
debuggable.apk: 1 file pushed. 60.9 MB/s (1377065 bytes in 0.022s)
        pkg: /data/local/tmp/debuggable.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]
```

I tried to install Version 1.3 and 1.2 on a rooted Android 6.0 emulator.
Installation of untrusted apps is allowed.

**Comment by fanhuanji** [comment]
i used the luckypatcher to resign the apk,and installed successfully
你需要幸运破解器

**Comment by whoot** [comment]
Worked!
However this is just a workaround.
@ttimasdf Please sign the app with a new/valid certificate.

**Comment by ttimasdf** [comment]
Ah..are you using OS below 6.0? I may forgot to tick the compatible option..:flushed:

**Comment by whoot** [comment]
Nope, i´m using Android 6.0 Marshmallow

**Comment by ttimasdf** [comment]
re-signed the apk. Check it out. [app-release.apk](https://github.com/ttimasdf/XDebuggable/releases/download/v1.3/app-release.apk)
```
01. app-release.apk

	VERIFY
	file: /path/to/XDebuggable/app/release/app-release.apk
	checksum: e6ca951ca43bfad629eaa5fe92842387f758f73aaeb3ba6db2542ac30c80451c (sha256)
	- zipalign verified
	- signature verified [v1, v2]
		Subject: CN=release, OU=Android, O=Known Rabbit, C=CN
		SHA256: ba2abde4a3341d083c436ee1546dc394630224be2fac8937ef1e2736d80aa269 / SHA256withRSA
		Expires: Tue Nov 25 12:16:27 CST 2042
```

**Comment by whoot** [comment]
Works! Thanks a lot!
